---
- name: Ensure activate file exists
  file:
    path: "{{ sync_folder_path }}"
    state: directory
- name: Conda init bash/zsh
  shell: ". {{activate_file}}; conda init bash; conda init zsh"
  args:
    executable: /bin/bash

- name: Read conda environment file
  slurp:
    src: "{{ environment_file }}"
  register: env_file_contents

- name: Get Environment name
  set_fact:
    environment_name: "{{ ((env_file_contents['content'] | b64decode) | from_yaml).name }}"

- name: Create conda environment
  shell: ". {{activate_file}}; conda env create -f {{ environment_file }}"
  ignore_errors: true
  args:
    executable: /bin/bash
  
- name: Add conda activate
  lineinfile:
    dest: "{{activate_file}}"
    create: yes
    state: present
    line: "conda activate {{ environment_name }}"

- name: conda env
  shell: ". {{activate_file}}; conda list"
  args:
    executable: /bin/bash
