---
  # tasks:
- name: Printout fs name
  debug:
    msg: "FS Name: {{ gcp_storage_name }} {{ gcp_project }} {{ gcp_cred_file }}"


- name: Create filesystem 
  gcp_storage_bucket:
    name: "{{ gcp_storage_name}}"
    project: "{{ gcp_project }}"
    auth_kind: "{{ gcp_cred_kind }}"
    service_account_file: "{{ gcp_cred_file }}"
    state: present
    location: "{{gcp_region}}"
    
