---
  # tasks:
- name: Printout fs name
  debug:
    msg: "FS Name: {{ gcp_storage_name }}"

- name: Delete all objects recursively
  command:
    cmd: "gsutil -m rm -r gs://{{gcp_storage_name}}"
- name: Check for filesystem existence
  gcp_storage_bucket:
    name: "{{ gcp_storage_name}}"
    project: "{{ gcp_project }}"
    auth_kind: "{{ gcp_cred_kind }}"
    service_account_file: "{{ gcp_cred_file }}"
    state: absent
    location: "{{ gcp_region }}"
    
