---

- name: Check for existing key
  file:
    state: absent
    path: "{{ gcp_ssh_private_key_file | default('keys/gcp') }}"
  ignore_errors: yes
  register: existing_private

- name: Check for existing key
  file:
    state: file
    path: "{{ gcp_ssh_private_key_file | default('keys/gcp') }}"
  ignore_errors: yes
  register: existing_private

- name: Printout existing private
  debug:
    msg: "{{ existing_private }}"

- name: Set private key path
  set_fact:
    gcp_ssh_private_key_file:  "{{ existing_private.path }}"

- name: Generate private key, register with gcp for service account os-login
  block:
    - name: Create openssh key
      openssh_keypair:
        path: "{{ existing_private.path }}"
        type: rsa
        size: 4096
        state: present
    - name: Store current gcloud account
      command: gcloud config get-value account
      register: prev_gcloud_account
    - name: Printout og gcloud account
      debug:
        msg: "Previous account: {{ prev_gcloud_account.stdout }}"
    - name: Switch to service account
      when: prev_gcloud_account.stdout != gcp_service_email
      command: "gcloud auth activate-service-account --key-file {{ gcp_cred_file }}"
    - name: Register new ssh key with service account os-login
      command: "gcloud compute os-login ssh-keys add --key-file {{ existing_private.path }}.pub"

    - name: Switch back to old gcp account if needed
      when: prev_gcloud_account.stdout != gcp_service_email
      command: "gcloud config set account {{ prev_gcloud_account.stdout }}"

      