---
hosts: !!omap
- racoon:
    status: unknown
    main_group: avery
    monkeyfs_public_ip: 192.168.99.41
    monkeyfs_public_port: '22'
- visiongpu06:
    status: init
    main_group: pulkit
    monkeyfs_public_ip: racoon.averylamp.me
    monkeyfs_public_port: '18022'
