---
- name: Conda init bash
  shell: . ~/.profile; conda init bash
  args:
    executable: /bin/bash

- name: Read conda environment file
  slurp:
    src: "{{ environment_file }}"
  register: env_file_contents

- name: Get Environment name
  set_fact:
    environment_name: "{{ ((env_file_contents['content'] | b64decode) | from_yaml).name }}"

- name: Create conda environment
  shell: . ~/.profile; conda env create -f "{{ environment_file }}"
  ignore_errors: true
  args:
    executable: /bin/bash
  
- name: Add conda activate
  lineinfile:
    dest: ~/.profile
    create: yes
    state: present
    line: "conda activate {{ environment_name }}"

- name: conda env
  shell: . ~/.profile; conda list
  args:
    executable: /bin/bash
