---

- name: Turn on ec2 Instance
  when:
    - existing_found is true
  amazon.aws.ec2:
    count_tag: 
      Name: "{{ monkey_job_uid }}"
    instance_type: "{{machine_type}}"
    instance_tags:
      Name: "{{ monkey_job_uid }}"
      Monkey: "Monkey_AWS"
    state: running
    wait: yes
    group: Monkey_Security_Group
    vpc_subnet_id: "{{monkey_subnet_id}}"
    region: "{{ aws_region }}"
    zone: "{{ aws_zone }}"
    volumes:
      - device_name: "/dev/sda1"
        delete_on_termination: true
        volume_size: "{{disk_size_gb}}"
        volume_type: "{{disk_type}}"
  register: existing_instance
- name: Create ec2 Instance
  when:
    - existing_found is false
  amazon.aws.ec2:
    exact_count: 1
    count_tag: 
      Name: "{{ monkey_job_uid }}"
    instance_type: "{{machine_type}}"
    instance_tags:
      Name: "{{ monkey_job_uid }}"
      Monkey: "Monkey_AWS"
    image: "{{base_image}}"
    key_name: "{{ aws_key_name }}"
    wait: yes
    group: Monkey_Security_Group
    vpc_subnet_id: "{{monkey_subnet_id}}"
    assign_public_ip: yes
    region: "{{ aws_region }}"
    zone: "{{ aws_zone }}"
    volumes:
      - device_name: "/dev/sda1"
        delete_on_termination: true
        volume_size: "{{disk_size_gb}}"
        volume_type: "{{disk_type}}"
  register: instance

- name: Set facts for existing 
  when:
    - existing_found is true
  set_fact:
    instance: "{{ existing_instance.instances.0 }}"
- name: Set facts for existing
  when:
    - existing_found is false
  set_fact:
    instance: "{{ instance.tagged_instances.0 }}"
