---
  # tasks:
# - name: Include AWS variables
#   include_vars:
#     file: "{{ gcp_cred_file }}"

- name: Set default instance params
  set_fact:
    disk_size_gb: "{{disk_size_gb | default('10')}}"
    disk_type: "{{disk_type | default('gp2')}}"
    machine_type: "{{machine_type | default('t2.micro')}}"
    base_image: "{{base_image | default('ami-0bcc094591f354be2')}}"

- name: Create ec2 Instance
  amazon.aws.ec2:
    exact_count: 1
    count_tag: 
      Name: "{{ monkey_job_uid }}"
    instance_type: "{{machine_type}}"
    instance_tags:
      Name: "{{ monkey_job_uid }}"
      Monkey: "Monkey_AWS"
    image: "{{base_image}}"
    key_name: "{{ aws_key_name }}"
    wait: yes
    group: Monkey_Security_Group
    vpc_subnet_id: "{{monkey_subnet_id}}"
    assign_public_ip: yes
    region: "{{ aws_region }}"
    zone: "{{ aws_zone }}"
    volumes:
      - device_name: "/dev/sda1"
        delete_on_termination: true
        volume_size: "{{disk_size_gb}}"
        volume_type: "{{disk_type}}"
  register: instance
- name:  Debug instance
  debug:
    msg: "{{ instance }}"

- name: Assert public ip address
  set_fact:
    public_ip: "{{ instance.tagged_instances.0.public_ip}}"
  register: found_public_ip
  until: found_public_ip is not failed
  delay: 5
  retries: 10
  ignore_errors: true

- name: Wait for SSH to come up
  wait_for: 
    host: "{{ public_ip }}"
    port: 22
    timeout: 15
  register: wait_for_ssh
  delay: 2
  until: wait_for_ssh is not failed
  retries: 5
  ignore_errors: true



- name: Get keyscan host key
  command: "ssh-keyscan -trsa  {{ public_ip }}"
  retries: 3
  delay: 2
  register: host_key_task
  until: host_key_task.rc == 0
- name: Set host key fact
  set_fact:
    host_key: "{{ host_key_task.stdout }}"

- name: Remove old known hosts
  lineinfile:
    dest: ~/.ssh/known_hosts
    create: yes
    state: absent
    regexp: "{{ public_ip }}.*"
- name: Add to known hosts
  lineinfile:
    dest: ~/.ssh/known_hosts
    create: yes
    state: present
    line: "{{ host_key }}"

- name: Add host to groupname
  add_host: 
    name: "{{ public_ip }}"
    groups:
      - "new_host"
    ansible_user: "ubuntu"
    ansible_ssh_private_key_file: "keys/{{ aws_key_name }}.pem"
