---
- name: Printout fs name
  debug:
    msg: "Mounting FS: {{ gcp_storage_name }}"

- name: Create Mountpoint
  ignore_errors: true
  become: true
  file:
    path: "{{monkeyfs_path}}"
    state: directory
    owner: "{{ ansible_user }}"
  register: create_mountpoint

- name: Debug create mountpoint
  debug: 
    msg: "Mountpoint {{create_mountpoint.failed}}; gcsfuse {{gcp_storage_name}} {{monkeyfs_path}}"
- name: Mount fs to Mountpoint
  when: create_mountpoint is not failed
  command:
    cmd: "gcsfuse {{gcp_storage_name}} {{monkeyfs_path}}"

