---

- name: Printout Command
  debug: 
    msg: "{{ run_command }}"
- name: template sync command
  template:
    src: templates/run.sh
    dest: ~/.run.sh
    mode: u=rwx,g=r,o=r
- name: Persist folder by running async rsync
  shell: . ~/.monkey_activate; ~/.run.sh
  async: 864000
  poll: 15
  args:
    executable: /bin/bash
  
