---
- name: Create venv folder
  shell: |
    python3 -m venv venv
    echo '. venv/bin/activate' >> {{activate_file}}; 
  args:
    executable: /bin/bash

- name: Create upgrade pip
  shell: |
    . {{activate_file}}
    pip install --upgrade pip

- name: Install requirements
  shell: . {{activate_file}}; pip install -r "{{ environment_file }}"
  args:
    executable: /bin/bash


