---
- hosts: localhost
  name: Locate AWS Bucket and Ensure permissions
  
  pre_tasks:
    - name: Import default vars
      include_vars:
        file: aws_vars.yml

  roles:
    - aws/setup_fs/create_fs
    - aws/setup_fs/mount_fs