---
aws_region: us-east-1
aws_key_name: monkey-aws
aws_zone: us-east-1c
firewall_rule: monkey-ansible-firewall
aws_ssh_private_key_path: keys/monkey-aws
storage_name: monkeyfs-qdbsss
monkeyfs_path: /monkeyfs
local_monkeyfs_path: /Users/avery/Developer/projects/monkey-project/monkey-core/ansible/monkeyfs-aws
