---
gcp_cred_kind: serviceaccount
gcp_cred_file: /Users/avery/Developer/projects/monkey-project/monkey-core/improbable-service-key.json
region: us-east1
zone: us-east1-b
firewall_rule: monkey-ansible-firewall
gcp_ssh_private_key_path:
gcp_storage_name:
monkeyfs_path:
