---
- hosts: localhost
  name: Create the GCP Machine
  
  pre_tasks:
    - name: Import default vars
      include_vars:
        file: gcp_vars.yml
    - name: Get variables from gcp private key
      set_fact:
        ansible_user: "sa_{{ (lookup('file', gcp_cred_file) | from_json).client_id }}"
        gcp_service_email: "{{ (lookup('file', gcp_cred_file) | from_json).client_email }}"
        gcp_project: "{{ (lookup('file', gcp_cred_file) | from_json).project_id }}"



  tasks:
    - name: Print out host ip
      debug:
        msg: "IP {{ public_ip }}"
  roles:
    - gcp/setup_keys
    - gcp/create



- hosts: new_host
  name: Configure New Host with Monkey Client
  gather_facts: no

  pre_tasks:
    - name: Display all variables/facts known for a host
      debug:
        var: hostvars[inventory_hostname]
        verbosity: 1
    - name: Import default vars
      include_vars:
        file: gcp_vars.yml
    - name: Get variables from gcp private key
      set_fact:
        ansible_user: "sa_{{ (lookup('file', gcp_cred_file) | from_json).client_id }}"
        gcp_project: "{{ (lookup('file', gcp_cred_file) | from_json).project_id }}"
    - name: Wait for connection
      wait_for_connection:
        timeout: 5
      delay: 2
      retries: 4
    - name: Setup host
      setup:
      register: result
      until: result is not failed
      ignore_errors: yes
      ignore_unreachable: yes
      retries: 3
      delay: 1
  tasks:
    - name: Finished installing monkey client
      debug:
        msg: "Finished installing monkey client: {{ inventory_hostname }}"
    
    - name: Setting name
      set_fact:
        new_gcp_host: "{{ inventory_hostname}}"
  roles:
    - gcp/install_deps
    - monkey_client/install
