---


- name: Turn on ec2 Instance Spot
  when:
    - existing_found is true
    - spot_price is defined
  amazon.aws.ec2:
    count_tag: 
      Name: "{{ monkey_job_uid }}"
    instance_type: "{{machine_type}}"
    instance_tags:
      Name: "{{ monkey_job_uid }}"
      Monkey: "Monkey_AWS"
      MonkeyStorage: "{{aws_storage_name}}"
    state: running
    wait: yes
    group: Monkey_Security_Group
    vpc_subnet_id: "{{monkey_subnet_id}}"
    region: "{{ aws_region }}"
    zone: "{{ aws_zone }}"
    volumes:
      - device_name: "/dev/sda1"
        delete_on_termination: true
        volume_size: "{{disk_size_gb}}"
        volume_type: "{{disk_type}}"
    spot_price: "{{ spot_price }}"
    spot_type: "one-time"
    spot_wait_timeout: 120
    instance_initiated_shutdown_behavior: "terminate"
  register: existing_instance_spot_price_defined


- name: Turn on ec2 Instance Spot
  when:
    - existing_found is true
    - spot_price is not defined
  amazon.aws.ec2:
    count_tag: 
      Name: "{{ monkey_job_uid }}"
    instance_type: "{{machine_type}}"
    instance_tags:
      Name: "{{ monkey_job_uid }}"
      Monkey: "Monkey_AWS"
      MonkeyStorage: "{{aws_storage_name}}"
    state: running
    wait: yes
    group: Monkey_Security_Group
    vpc_subnet_id: "{{monkey_subnet_id}}"
    region: "{{ aws_region }}"
    zone: "{{ aws_zone }}"
    volumes:
      - device_name: "/dev/sda1"
        delete_on_termination: true
        volume_size: "{{disk_size_gb}}"
        volume_type: "{{disk_type}}"
    spot_type: "one-time"
    spot_price: 100
    spot_wait_timeout: 120
    instance_initiated_shutdown_behavior: "terminate"
  register: existing_instance_spot_max_price

- name: Create ec2 Instance Spot
  when:
    - existing_found is false
    - spot_price is defined
  amazon.aws.ec2:
    exact_count: 1
    count_tag: 
      Name: "{{ monkey_job_uid }}"
    instance_type: "{{machine_type}}"
    instance_tags:
      Name: "{{ monkey_job_uid }}"
      Monkey: "Monkey_AWS"
      MonkeyStorage: "{{aws_storage_name}}"
    image: "{{base_image}}"
    key_name: "{{ aws_key_name }}"
    wait: yes
    group: Monkey_Security_Group
    vpc_subnet_id: "{{monkey_subnet_id}}"
    assign_public_ip: yes
    region: "{{ aws_region }}"
    zone: "{{ aws_zone }}"
    volumes:
      - device_name: "/dev/sda1"
        delete_on_termination: true
        volume_size: "{{disk_size_gb}}"
        volume_type: "{{disk_type}}"
    spot_price: "{{spot_price}}"
    spot_type: "one-time"
    spot_wait_timeout: 120
    instance_initiated_shutdown_behavior: "terminate"
  register: instance_spot_price_defined

- name: Create ec2 Instance Spot
  when:
    - existing_found is false
    - spot_price is not defined
  amazon.aws.ec2:
    exact_count: 1
    count_tag: 
      Name: "{{ monkey_job_uid }}"
    instance_type: "{{machine_type}}"
    instance_tags:
      Name: "{{ monkey_job_uid }}"
      Monkey: "Monkey_AWS"
      MonkeyStorage: "{{aws_storage_name}}"
    image: "{{base_image}}"
    key_name: "{{ aws_key_name }}"
    wait: yes
    group: Monkey_Security_Group
    vpc_subnet_id: "{{monkey_subnet_id}}"
    assign_public_ip: yes
    region: "{{ aws_region }}"
    zone: "{{ aws_zone }}"
    volumes:
      - device_name: "/dev/sda1"
        delete_on_termination: true
        volume_size: "{{disk_size_gb}}"
        volume_type: "{{disk_type}}"
    spot_type: "one-time"
    spot_price: 100
    spot_wait_timeout: 120
    instance_initiated_shutdown_behavior: "terminate"
  register: instance_spot_max_price

- name: Debug
  debug:
    msg: "{{ existing_instance_spot_price_defined}}\n {{ existing_instance_spot_max_price}} \n{{instance_spot_price_defined}}\n{{ instance_spot_max_price }}"


- name: Set facts for existing spot set price
  when:
    - existing_found is true
    - spot_price is defined
    - spot is true
  set_fact:
    instance: "{{ existing_instance_spot_price_defined.instances.0 }}"

- name: Set facts for existing spot max price
  when:
    - existing_found is true
    - spot_price is not defined
    - spot is true
  set_fact:
    instance: "{{ existing_instance_spot_max_price.instances.0 }}"

- name: Set facts for existing spot set price
  when:
    - existing_found is false
    - spot_price is defined
    - spot is true
  set_fact:
    instance: "{{ instance_spot_price_defined.tagged_instances.0 }}"

- name: Set facts for existing spot max price
  when:
    - existing_found is false
    - spot_price is not defined
    - spot is true
  set_fact:
    instance: "{{ instance_spot_max_price.tagged_instances.0 }}"


- name: Debug instance
  debug:
    msg: "Instance: {{instance}}"
