---
  # tasks:
- name: Default fs name
  set_fact:
    gcp_project: "{{ (lookup('file', gcp_cred_file) | from_json).project_id }}"
- name: Printout fs name
  debug:
    msg: "FS Name: {{ storage_name }}"

- name: Delete all objects recursively
  command:
    cmd: "gsutil -m rm -r gs://{{storage_name}}"
- name: Check for filesystem existence
  gcp_storage_bucket:
    name: "{{ storage_name}}"
    project: "{{ gcp_project }}"
    auth_kind: "{{ gcp_cred_kind }}"
    service_account_file: "{{ gcp_cred_file }}"
    state: absent
    location: "{{ gcp_region }}"
    
