---
# TODO: ensure copying of data over with shutdown script
- name: Delete a instance
  ec2:
      exact_count: 1
      count_tag: 
        Name: "{{ monkey_job_uid }}"
      instance_type: t2.nano
      instance_tags:
        Name: "{{ monkey_job_uid }}"
        Monkey: "Monkey_AWS"
      image: ami-0bcc094591f354be2
      key_name: "{{ aws_key_name }}"
      wait: yes
      group: Monkey_Security_Group
      vpc_subnet_id: "{{monkey_subnet_id}}"
      assign_public_ip: yes
      region: "{{ aws_region }}"
      zone: "{{ aws_zone }}"
  register: existing_instance

- name: Set instance_id Fact
  set_fact:
    instance_id: "{{existing_instance.tagged_instances.0.id}}"

- name: Printout instance info
  debug:
    msg: "Instance info: {{existing_instance}}"

- name: Delete the instance
  ec2:
    instance_id: "{{instance_id}}"
    vpc_subnet_id: "{{monkey_subnet_id}}"
    assign_public_ip: yes
    region: "{{ aws_region }}"
    zone: "{{ aws_zone }}"
    state: absent



