---
plugin: gcp_compute
projects:
  - monkey-274001
regions:
  - us-east1
keyed_groups:
  - key: zone
groups:
  monkey: "'monkey' in name"
  monkey_gcp: "'monkey' in name"
hostnames:
  - name
filters: []
auth_kind: serviceaccount
service_account_file: /Users/avery/Developer/projects/monkey-project/monkey/gcp-service-key-personal.json
compose:
  ansible_host: networkInterfaces[0].accessConfigs[0].natIP