---
plugin: gcp_compute
projects: [improbable-ai-avery-971c]
regions: [us-east1]
keyed_groups: [key: zone]
groups: {monkey: "'monkey` in name", monkey_gcp: "'monkey` in name"}
hostnames: [name]
filters: []
auth_kind: serviceaccount
service_account_file: /Users/avery/Developer/projects/monkey-project/monkey-core/improbable-service-key.json
compose: {ansible_host: 'networkInterfaces[0].accessConfigs[0].natIP'}
