---

- name: Check for docker
  command: docker run hello-world
  register: docker_found
  ignore_errors: true

- name: Install docker if not found
  when: docker_found.rc != 0
  block:
    - name: Install required system packages
      become: true
      apt: name={{ item }} state=latest update_cache=yes
      loop:
        - apt-transport-https
        - ca-certificates
        - curl
        - software-properties-common
        - python3-pip
        - virtualenv
        - python3-setuptools

    - name: Add Docker GPG apt Key
      become: true
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker Repository
      become: true
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu bionic stable
        state: present

    - name: Update apt and install docker-ce
      become: true
      apt: update_cache=yes name=docker-ce state=latest

    - name: Install Docker Module for Python
      become: true
      pip:
        name: docker

    - name: Add ansible user to docker group
      debug:
        msg: "user {{ ansible_user }}"
    - name: Add ansible user to docker group
      become: true
      user:
        name: "{{ ansible_user }}"
        group: docker
        append: true

- name: Check for existing nvidia-docker2
  command: nvidia-docker --version
  register: nvidia_docker_found
  ignore_errors: true

- name: Install nvidia-docker if not found
  when: nvidia_docker_found.rc != 0
  block:
    - name: Get distribution String
      shell: echo $(. /etc/os-release;echo $ID$VERSION_ID)
      register: distribution

    - name: Add Nvidia-Docker GPG apt key
      become: true
      apt_key:
        url: "https://nvidia.github.io/nvidia-docker/gpgkey"
        state: present

    - name: Print url
      debug:
        msg: "https://nvidia.github.io/nvidia-docker/{{ distribution.stdout }}/nvidia-docker.list"

    - name: Add NVidia-Docker repository source
      become: true
      get_url:
        url: "https://nvidia.github.io/nvidia-docker/{{ distribution.stdout }}/nvidia-docker.list"
        dest: /etc/apt/sources.list.d/nvidia-docker.list
        owner: root
        group: root
        mode: 0644

    - name: Apt install nvidia-docker2
      become: true
      apt:
        name:
          - nvidia-docker2
        update_cache: true

    - name: Reload Docker Service
      become: true
      systemd:
        name: docker
        state: restarted





