---
- hosts: localhost
  name: Create the GCP Machine
  
  pre_tasks:
    - name: Import default vars
      include_vars:
        file: create_job_vars.yml
    - name: Get variables from gcp private key
      set_fact:
        ansible_user: "sa_{{ (lookup('file', gcp_cred_file) | from_json).client_id }}"
        gcp_project: "{{ (lookup('file', gcp_cred_file) | from_json).project_id }}"


  tasks:
    - name: Print out host ip
      debug:
        msg: "IP {{ public_ip }}"
  roles:
    - gcp/create

- hosts: new_host
  name: Configure New Host with Monkey Client
  gather_facts: no

  pre_tasks:
    - name: Import default vars
      include_vars:
        file: create_job_vars.yml
    - name: Get variables from gcp private key
      set_fact:
        ansible_user: "sa_{{ (lookup('file', gcp_cred_file) | from_json).client_id }}"
        gcp_project: "{{ (lookup('file', gcp_cred_file) | from_json).project_id }}"
    - name: Setup host
      setup:

  tasks:
    - name: Finished installing monkey client
      debug:
        msg: "Finished installing monkey client"

  roles:
    - monkey_client/install
