---
- hosts: localhost
  name: Create the AWS machine
  
  pre_tasks:
    - name: Import default vars
      include_vars:
        file: aws_vars.yml

  roles:
    - aws/create

- hosts: new_host
  name: Configure New Host with Monkey Client
  gather_facts: no

  pre_tasks:
    - name: Import default vars
      include_vars:
        file: aws_vars.yml
    - name: Wait for connection
      wait_for_connection:
        timeout: 15
      delay: 2
    - name: Setup host
      setup:
      register: result
      until: result is not failed
      ignore_errors: yes
      ignore_unreachable: yes
      retries: 3
      delay: 1
  tasks:
    - name: Finished installing monkey client
      debug:
        msg: "Finished installing monkey client: {{ inventory_hostname }}"
    
    - name: Setting name
      set_fact:
        new_aws_host: "{{ inventory_hostname}}"
  roles:
    - aws/install_deps
    - monkey_client/install
