---
- hosts: localhost
  name: Remove all keys associated to os-login for the service account
  
  pre_tasks:
    - name: Import default vars
      include_vars:
        file: gcp_vars.yml

  roles:
    - gcp/remove_keys

