---
- hosts: localhost
  name: Locate GCS Bucket and Ensure permissions
  
  pre_tasks:
    - name: Import default vars
      include_vars:
        file: gcp_vars.yml

  roles:
    - gcp/setup/setup_keys
    - gcp/setup/setup_vpc
    - gcp/setup/create_fs
    - gcp/setup/mount_fs
