---
- hosts: localhost
  name: Locate GCS Bucket and Ensure permissions
  
  pre_tasks:
    - name: Import default vars
      include_vars:
        file: gcp_vars.yml
    - name: Get variables from gcp private key
      set_fact:
        gcp_project: "{{ (lookup('file', gcp_cred_file) | from_json).project_id }}"
        gcp_service_email: "{{ (lookup('file', gcp_cred_file) | from_json).client_email }}"

  roles:
    - gcp/setup/setup_keys
    - gcp/setup/setup_vpc
    - gcp/setup/create_fs
    - gcp/setup/mount_fs
