---
- hosts: localhost
  name: Install GCS Bucket and Mount it
  
  pre_tasks:
    - name: Import default vars
      include_vars:
        file: gcp_vars.yml
    - name: Get variables from gcp private key
      set_fact:
        gcp_project: "{{ (lookup('file', gcp_cred_file) | from_json).project_id }}"

  roles:
    - gcp/setup/create_fs
