---
  # tasks:
- name: Get fs name
  set_fact:
    aws_storage_name: "{{ aws_storage_name }}"
    monkeyfs_path: "{{monkeyfs_path}}"
- name: Printout fs name
  debug:
    msg: "Mounting FS: {{ aws_storage_name }}"

- name: Create Mountpoint
  ignore_errors: true
  become: true
  file:
    path: "{{monkeyfs_path}}"
    state: directory
    owner: "{{ ansible_user }}"
  register: create_mountpoint

- name: Debug create mountpoint
  debug: 
    msg: "Mountpoint {{create_mountpoint.failed}}"
- name: Mount fs to Mountpoint
  when: create_mountpoint is not failed

  command:
    environment:
        "AWS_ACCESS_KEY_ID": "{{access_key_id}}"
        "AWS_SECRET_ACCESS_KEY": "{{access_key_secret}}"
    cmd: "s3fs {{aws_storage_name}} {{monkeyfs_path}}"

