---
- name: Printout command
  debug:
    msg: "while true; do rsync -r {{ persist_folder_path }} {{ bucket_path }}; sleep 15; done"
- name: template sync command
  template:
    src: templates/sync_loop.sh
    dest: "{{ persist_script_path }}"
    mode: u=rwx,g=r,o=r
- name: Persist folder by running async rsync
  shell: "{{ persist_script_path }}"
  args:
    executable: /bin/bash
  async: 2592000               # 60*60*24*30 – 1 month
  poll: 0
