---
- name: 20.04 Install Script
  debug:
    msg: "20.04 script running"

- name: Download CUDA pin
  become: true
  get_url:
    url: https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2004/x86_64/cuda-ubuntu2004.pin  
    dest: /etc/apt/preferences.d/cuda-repository-pin-600
- name: Get Apt Key
  become: true
  apt_key:
    url: https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2004/x86_64/7fa2af80.pub
    state: present

- name: Get Apt Repository
  become: true
  apt_repository:
    repo: deb https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2004/x86_64/ / 

- name: Install CUDA package
  become: true
  async: 1200
  poll: 5
  apt:
    name: cuda
    update_cache: yes

- name: Install CUDA Toolkit
  become: true
  async: 1200
  poll: 5
  apt:
    name: nvidia-cuda-toolkit
    update_cache: yes

- name: Download cuDNN tarball
  become: true
  ignore_errors: yes
  get_url:
    url: https://developer.download.nvidia.com/compute/machine-learning/cudnn/secure/8.0.4/11.1_20200923/cudnn-11.1-linux-x64-v8.0.4.30.tgz?kK7raFWXHvWQjinF93zUlvE6fFfknpAnFG77DrptKWdXISkyreqf6H4tvc6HciG9bE6qIgAEtKneA8SY2dIq9JNb89LQdHOnTcKfrUHt6pJkMrG_GqGOKJmaaCKUhdni07h7r8ZDeHozP6ezkdKTHURVUHAa8w5OSJs60hVOEF-4pgloq68ADYu9am_nJiMwejU96Ru_k74NAj0
    dest: /tmp/cudnn.tgz
 
- name: Install cuDNN deb
  become: true
  ignore_errors: yes
  shell:
    cmd: tar -xzvf /tmp/cudnn.tgz -C /tmp

- name: Copy 
  become: true
  ignore_errors: yes
  shell: |
    cp /tmp/cuda/include/cudnn*.h /usr/local/cuda/include
    cp /tmp/cuda/lib64/libcudnn* /usr/local/cuda/lib64
    chmod a+r /usr/local/cuda/include/cudnn*.h /usr/local/cuda/lib64/libcudnn*

     
