# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: MNIST Test

on:
  push:
    branches: [ master, develop, actions ]
  pull_request:
    branches: [ master, develop ]

jobs:
  build:
    runs-on: seacow

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r monkey-core/requirements.txt
        
